node {
    withCredentials([usernamePassword(credentialsId: 'azure-boards', usernameVariable: 'USERNAME', passwordVariable: 'AZURE_TOKEN')]) {
        sh label: 'Qry boards', script: """
        curl -v -X GET \
        -u $USERNAME:$AZURE_TOKEN \
        https://dev.azure.com/alondannel/My%20DevOps%20Project/_apis/wit/workitems/2?api-version=5.1
        """
    }
}

